version: "3"

services:
  redis:
    image: redis:6.0-alpine
    container_name: redis-master
    command: redis-server /etc/redis/redis.conf
    volumes:
      - ./master:/etc/redis/
    ports:
      - 6379:6379
    networks:
      - lan-redis

  sentinel:
    image: redis:6.0-alpine
    container_name: sentinel-master
    command: redis-sentinel /etc/redis/sentinel.conf
    volumes:
      - ./master:/etc/redis/
    ports:
      - 26379:26379
    networks:
      - lan-redis

  redis-slave:
    image: redis:6.0-alpine

    command: redis-server /etc/redis/redis.conf
    volumes:
      - ./slave:/etc/redis/
    ports:
      - 6370-6378:6379
    networks:
      - lan-redis

  sentinel-slave:
    image: redis:6.0-alpine

    command: redis-sentinel /etc/redis/sentinel.conf
    volumes:
      - ./slave:/etc/redis/
    ports:
      - 26370-26378:26379
    networks:
      - lan-redis
networks:
  lan-redis:
    driver: bridge
